// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using clean.data;

#nullable disable

namespace clean.data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250722152445_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("clean.core.Entities.Albums", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NameAlbums")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameCertore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SingerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SingerId");

                    b.ToTable("dataAlbums");
                });

            modelBuilder.Entity("clean.core.Entities.Singer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("dataSinger");
                });

            modelBuilder.Entity("clean.core.Entities.Songs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AlbumsId")
                        .HasColumnType("int");

                    b.Property<string>("NameCertore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameSonges")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SingerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumsId");

                    b.HasIndex("SingerId");

                    b.ToTable("dataSonges");
                });

            modelBuilder.Entity("clean.core.Entities.Albums", b =>
                {
                    b.HasOne("clean.core.Entities.Singer", null)
                        .WithMany("Albums")
                        .HasForeignKey("SingerId");
                });

            modelBuilder.Entity("clean.core.Entities.Songs", b =>
                {
                    b.HasOne("clean.core.Entities.Albums", null)
                        .WithMany("Songs")
                        .HasForeignKey("AlbumsId");

                    b.HasOne("clean.core.Entities.Singer", null)
                        .WithMany("Songs")
                        .HasForeignKey("SingerId");
                });

            modelBuilder.Entity("clean.core.Entities.Albums", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("clean.core.Entities.Singer", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
